// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TextMsgRequest.proto

package com.coy.gupaoedu.study.serialization.proto;

public final class TextMsgRequestProto {
  private TextMsgRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.hs.dingtalk.proto.ResponseCode}
   */
  public enum ResponseCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RESP_CODE_SUCCESS = 0;</code>
     */
    RESP_CODE_SUCCESS(0),
    /**
     * <code>RESP_CODE_FAILED = 1;</code>
     */
    RESP_CODE_FAILED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RESP_CODE_SUCCESS = 0;</code>
     */
    public static final int RESP_CODE_SUCCESS_VALUE = 0;
    /**
     * <code>RESP_CODE_FAILED = 1;</code>
     */
    public static final int RESP_CODE_FAILED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ResponseCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCode forNumber(int value) {
      switch (value) {
        case 0: return RESP_CODE_SUCCESS;
        case 1: return RESP_CODE_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseCode>() {
            public ResponseCode findValueByNumber(int number) {
              return ResponseCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return TextMsgRequestProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseCode[] VALUES = values();

    public static ResponseCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hs.dingtalk.proto.ResponseCode)
  }

  public interface TextMsgRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hs.dingtalk.proto.TextMsgRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户id列表
     * </pre>
     *
     * <code>string useridList = 1;</code>
     */
    String getUseridList();
    /**
     * <pre>
     * 用户id列表
     * </pre>
     *
     * <code>string useridList = 1;</code>
     */
    com.google.protobuf.ByteString
        getUseridListBytes();

    /**
     * <pre>
     * 部门id列表
     * </pre>
     *
     * <code>string deptIdList = 2;</code>
     */
    String getDeptIdList();
    /**
     * <pre>
     * 部门id列表
     * </pre>
     *
     * <code>string deptIdList = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeptIdListBytes();

    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    String getContent();
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.hs.dingtalk.proto.TextMsgRequest}
   */
  public  static final class TextMsgRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hs.dingtalk.proto.TextMsgRequest)
      TextMsgRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextMsgRequest.newBuilder() to construct.
    private TextMsgRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextMsgRequest() {
      useridList_ = "";
      deptIdList_ = "";
      content_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextMsgRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              useridList_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deptIdList_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_TextMsgRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_TextMsgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TextMsgRequest.class, Builder.class);
    }

    public static final int USERIDLIST_FIELD_NUMBER = 1;
    private volatile Object useridList_;
    /**
     * <pre>
     * 用户id列表
     * </pre>
     *
     * <code>string useridList = 1;</code>
     */
    public String getUseridList() {
      Object ref = useridList_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        useridList_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户id列表
     * </pre>
     *
     * <code>string useridList = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUseridListBytes() {
      Object ref = useridList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        useridList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPTIDLIST_FIELD_NUMBER = 2;
    private volatile Object deptIdList_;
    /**
     * <pre>
     * 部门id列表
     * </pre>
     *
     * <code>string deptIdList = 2;</code>
     */
    public String getDeptIdList() {
      Object ref = deptIdList_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deptIdList_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 部门id列表
     * </pre>
     *
     * <code>string deptIdList = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeptIdListBytes() {
      Object ref = deptIdList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deptIdList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile Object content_;
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUseridListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, useridList_);
      }
      if (!getDeptIdListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deptIdList_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUseridListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, useridList_);
      }
      if (!getDeptIdListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deptIdList_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TextMsgRequest)) {
        return super.equals(obj);
      }
      TextMsgRequest other = (TextMsgRequest) obj;

      boolean result = true;
      result = result && getUseridList()
          .equals(other.getUseridList());
      result = result && getDeptIdList()
          .equals(other.getDeptIdList());
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERIDLIST_FIELD_NUMBER;
      hash = (53 * hash) + getUseridList().hashCode();
      hash = (37 * hash) + DEPTIDLIST_FIELD_NUMBER;
      hash = (53 * hash) + getDeptIdList().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TextMsgRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextMsgRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextMsgRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextMsgRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextMsgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextMsgRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextMsgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TextMsgRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TextMsgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TextMsgRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TextMsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TextMsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TextMsgRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hs.dingtalk.proto.TextMsgRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hs.dingtalk.proto.TextMsgRequest)
        TextMsgRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_TextMsgRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_TextMsgRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TextMsgRequest.class, Builder.class);
      }

      // Construct using com.coy.gupaoedu.study.serialization.proto.TextMsgRequestProto.TextMsgRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        useridList_ = "";

        deptIdList_ = "";

        content_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_TextMsgRequest_descriptor;
      }

      @Override
      public TextMsgRequest getDefaultInstanceForType() {
        return TextMsgRequest.getDefaultInstance();
      }

      @Override
      public TextMsgRequest build() {
        TextMsgRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TextMsgRequest buildPartial() {
        TextMsgRequest result = new TextMsgRequest(this);
        result.useridList_ = useridList_;
        result.deptIdList_ = deptIdList_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TextMsgRequest) {
          return mergeFrom((TextMsgRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TextMsgRequest other) {
        if (other == TextMsgRequest.getDefaultInstance()) return this;
        if (!other.getUseridList().isEmpty()) {
          useridList_ = other.useridList_;
          onChanged();
        }
        if (!other.getDeptIdList().isEmpty()) {
          deptIdList_ = other.deptIdList_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TextMsgRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TextMsgRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object useridList_ = "";
      /**
       * <pre>
       * 用户id列表
       * </pre>
       *
       * <code>string useridList = 1;</code>
       */
      public String getUseridList() {
        Object ref = useridList_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          useridList_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 用户id列表
       * </pre>
       *
       * <code>string useridList = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUseridListBytes() {
        Object ref = useridList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          useridList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户id列表
       * </pre>
       *
       * <code>string useridList = 1;</code>
       */
      public Builder setUseridList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        useridList_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户id列表
       * </pre>
       *
       * <code>string useridList = 1;</code>
       */
      public Builder clearUseridList() {
        
        useridList_ = getDefaultInstance().getUseridList();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户id列表
       * </pre>
       *
       * <code>string useridList = 1;</code>
       */
      public Builder setUseridListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        useridList_ = value;
        onChanged();
        return this;
      }

      private Object deptIdList_ = "";
      /**
       * <pre>
       * 部门id列表
       * </pre>
       *
       * <code>string deptIdList = 2;</code>
       */
      public String getDeptIdList() {
        Object ref = deptIdList_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deptIdList_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 部门id列表
       * </pre>
       *
       * <code>string deptIdList = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeptIdListBytes() {
        Object ref = deptIdList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deptIdList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 部门id列表
       * </pre>
       *
       * <code>string deptIdList = 2;</code>
       */
      public Builder setDeptIdList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deptIdList_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 部门id列表
       * </pre>
       *
       * <code>string deptIdList = 2;</code>
       */
      public Builder clearDeptIdList() {
        
        deptIdList_ = getDefaultInstance().getDeptIdList();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 部门id列表
       * </pre>
       *
       * <code>string deptIdList = 2;</code>
       */
      public Builder setDeptIdListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deptIdList_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 文本内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hs.dingtalk.proto.TextMsgRequest)
    }

    // @@protoc_insertion_point(class_scope:com.hs.dingtalk.proto.TextMsgRequest)
    private static final TextMsgRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TextMsgRequest();
    }

    public static TextMsgRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextMsgRequest>
        PARSER = new com.google.protobuf.AbstractParser<TextMsgRequest>() {
      @Override
      public TextMsgRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextMsgRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextMsgRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TextMsgRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public TextMsgRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendMsgResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hs.dingtalk.proto.SendMsgResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求是否成功编码
     * </pre>
     *
     * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
     */
    int getCodeValue();
    /**
     * <pre>
     * 请求是否成功编码
     * </pre>
     *
     * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
     */
    ResponseCode getCode();

    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    String getMsg();
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <pre>
     * 钉钉返回的异步消息任务id
     * </pre>
     *
     * <code>int64 data = 3;</code>
     */
    long getData();
  }
  /**
   * Protobuf type {@code com.hs.dingtalk.proto.SendMsgResponse}
   */
  public  static final class SendMsgResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hs.dingtalk.proto.SendMsgResponse)
      SendMsgResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendMsgResponse.newBuilder() to construct.
    private SendMsgResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMsgResponse() {
      code_ = 0;
      msg_ = "";
      data_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendMsgResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              data_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_SendMsgResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_SendMsgResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SendMsgResponse.class, Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * 请求是否成功编码
     * </pre>
     *
     * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <pre>
     * 请求是否成功编码
     * </pre>
     *
     * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
     */
    public ResponseCode getCode() {
      @SuppressWarnings("deprecation")
      ResponseCode result = ResponseCode.valueOf(code_);
      return result == null ? ResponseCode.UNRECOGNIZED : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 响应消息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private long data_;
    /**
     * <pre>
     * 钉钉返回的异步消息任务id
     * </pre>
     *
     * <code>int64 data = 3;</code>
     */
    public long getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != ResponseCode.RESP_CODE_SUCCESS.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (data_ != 0L) {
        output.writeInt64(3, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != ResponseCode.RESP_CODE_SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (data_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SendMsgResponse)) {
        return super.equals(obj);
      }
      SendMsgResponse other = (SendMsgResponse) obj;

      boolean result = true;
      result = result && code_ == other.code_;
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getData()
          == other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getData());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SendMsgResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendMsgResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendMsgResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendMsgResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendMsgResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SendMsgResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SendMsgResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SendMsgResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SendMsgResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SendMsgResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SendMsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SendMsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SendMsgResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hs.dingtalk.proto.SendMsgResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hs.dingtalk.proto.SendMsgResponse)
        SendMsgResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_SendMsgResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_SendMsgResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SendMsgResponse.class, Builder.class);
      }

      // Construct using com.coy.gupaoedu.study.serialization.proto.TextMsgRequestProto.SendMsgResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        data_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextMsgRequestProto.internal_static_com_hs_dingtalk_proto_SendMsgResponse_descriptor;
      }

      @Override
      public SendMsgResponse getDefaultInstanceForType() {
        return SendMsgResponse.getDefaultInstance();
      }

      @Override
      public SendMsgResponse build() {
        SendMsgResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SendMsgResponse buildPartial() {
        SendMsgResponse result = new SendMsgResponse(this);
        result.code_ = code_;
        result.msg_ = msg_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SendMsgResponse) {
          return mergeFrom((SendMsgResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SendMsgResponse other) {
        if (other == SendMsgResponse.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getData() != 0L) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SendMsgResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SendMsgResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <pre>
       * 请求是否成功编码
       * </pre>
       *
       * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <pre>
       * 请求是否成功编码
       * </pre>
       *
       * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求是否成功编码
       * </pre>
       *
       * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
       */
      public ResponseCode getCode() {
        @SuppressWarnings("deprecation")
        ResponseCode result = ResponseCode.valueOf(code_);
        return result == null ? ResponseCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求是否成功编码
       * </pre>
       *
       * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
       */
      public Builder setCode(ResponseCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求是否成功编码
       * </pre>
       *
       * <code>.com.hs.dingtalk.proto.ResponseCode code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应消息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private long data_ ;
      /**
       * <pre>
       * 钉钉返回的异步消息任务id
       * </pre>
       *
       * <code>int64 data = 3;</code>
       */
      public long getData() {
        return data_;
      }
      /**
       * <pre>
       * 钉钉返回的异步消息任务id
       * </pre>
       *
       * <code>int64 data = 3;</code>
       */
      public Builder setData(long value) {
        
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 钉钉返回的异步消息任务id
       * </pre>
       *
       * <code>int64 data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hs.dingtalk.proto.SendMsgResponse)
    }

    // @@protoc_insertion_point(class_scope:com.hs.dingtalk.proto.SendMsgResponse)
    private static final SendMsgResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SendMsgResponse();
    }

    public static SendMsgResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMsgResponse>
        PARSER = new com.google.protobuf.AbstractParser<SendMsgResponse>() {
      @Override
      public SendMsgResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMsgResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendMsgResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SendMsgResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public SendMsgResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hs_dingtalk_proto_TextMsgRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hs_dingtalk_proto_TextMsgRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hs_dingtalk_proto_SendMsgResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hs_dingtalk_proto_SendMsgResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024TextMsgRequest.proto\022\025com.hs.dingtalk." +
      "proto\"I\n\016TextMsgRequest\022\022\n\nuseridList\030\001 " +
      "\001(\t\022\022\n\ndeptIdList\030\002 \001(\t\022\017\n\007content\030\003 \001(\t" +
      "\"_\n\017SendMsgResponse\0221\n\004code\030\001 \001(\0162#.com." +
      "hs.dingtalk.proto.ResponseCode\022\013\n\003msg\030\002 " +
      "\001(\t\022\014\n\004data\030\003 \001(\003*;\n\014ResponseCode\022\025\n\021RES" +
      "P_CODE_SUCCESS\020\000\022\024\n\020RESP_CODE_FAILED\020\001BA" +
      "\n*com.coy.gupaoedu.study.serialization.p" +
      "rotoB\023TextMsgRequestProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hs_dingtalk_proto_TextMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hs_dingtalk_proto_TextMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hs_dingtalk_proto_TextMsgRequest_descriptor,
        new String[] { "UseridList", "DeptIdList", "Content", });
    internal_static_com_hs_dingtalk_proto_SendMsgResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hs_dingtalk_proto_SendMsgResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hs_dingtalk_proto_SendMsgResponse_descriptor,
        new String[] { "Code", "Msg", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
