FROM openjdk:8-jre-alpine
MAINTAINER chenck
LABEL name="study-mybatis-plus" version="1.0" author="chenck"
COPY study-mybatis-plus.jar study-mybatis-plus.jar
CMD ["java","-jar","study-mybatis-plus.jar"]