server:
  port: 8081
  #servlet:
  #  context-path: /l2cache-example

logging:
  level:
    root: info
    # 日志级别指定到包或类
    com.coy.l2cache: debug

spring:
  application:
    name: study-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080