spring:
  application:
    name: study-spring-demo
  profiles:
    # 注意: spring.profiles.active 配置在该配置文件中可能不生效，可在启动的环境变量中增加 spring.profiles.active=dev
    active: test
  # 缓存
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=5s

server:
  port: 8080
  #servlet:
  #  context-path: /study-mybatis-plus

