server:
  port: 8080
  #servlet:
  #  context-path: /study-spring-demo

spring:
  application:
    name: study-spring-demo
  profiles:
    # 注意: spring.profiles.active 配置在该配置文件中可能不生效，可在启动的环境变量中增加 spring.profiles.active=dev
    active: test
  # 缓存
  cache:
    # 一级缓存
    #type: caffeine
    #caffeine:
    #  spec: initialCapacity=10,maximumSize=200,expireAfterWrite=5s
    # 多级缓存
    multi:
      caffeine:
        spec: initialCapacity=10,maximumSize=200,expireAfterWrite=5s
      redis:
        defaultTimeToLive: 1000
        expires:
          test1: 1000
          test2: 2000
          test3: 3000


