server:
  port: 8000
spring:
  security:
    oauth2:
      client:
        registration:
          # github OAuth 应用
          github:
            client-id: bd2b30459e4de228d704
            client-secret: 669e02726283a7748686abcc69bccedd308579af
            # 与github中的callback URL保持一致
            redirect-uri: http://oauth2login:8000/login/oauth2/code/messaging-client
          # 自定义 OAuth 应用
          messaging-client:
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,message.read,message.write
            # 重定向url与Server中的RegisteredClient的redirectUri(url)保持一致
            redirect-uri: http://oauth2login:8000/login/oauth2/code/messaging-client
            provider: messaging-client
            client-name: messaging-client
        provider:
          messaging-client:
#            authorization-uri: http://oauth2server:8080/oauth2/authorize
#            token-uri: http://oauth2server:8080/oauth2/token
#            jwk-set-uri: http://oauth2server:8080/oauth2/jwks
#            user-info-uri: http://oauth2server:8080/userinfo
#            user-name-attribute: sub
            #单独配置如下一个也是可以的，底层会自动寻址，如果自定义过url，需要使用上面方式配置(修改oauthserve里上面那些url后，使用如下配置能否有效未测试)
            issuer-uri: http://oauth2server:9000